### ISSUE TITLE
Compilation failure

### ISSUE THREAD

**Issue by vadimtk** [Percona-Lab/query-playback#27]
[ 36%] Building CXX object percona_playback/query_log/CMakeFiles/query_log.dir/query_log.cc.o
/opt/vadim/query/query-playback/percona_playback/query_log/query_log.cc:55:8: error: â€˜atomicâ€™ in namespace â€˜boostâ€™ does not name a type
 static boost::atomic<long long> g_max_behind_ns;
        ^
/opt/vadim/query/query-playback/percona_playback/query_log/query_log.cc: In function â€˜bool parse_time(boost::string_ref, QueryLogEntry::TimePoint&)â€™:
/opt/vadim/query/query-playback/percona_playback/query_log/query_log.cc:89:27: error: â€˜boost::string_refâ€™ has no member named â€˜to_stringâ€™
   int num_read = sscanf(s.to_string().c_str(), "# Time: %02d%02d%02d %2d:%02d:%02d.%06lld",

**Comment by vadimtk** [comment]
@undingen I wonder if you know what it is

**Comment by undingen** [comment]
Oh sorry it looks like accidentely I added some boost >= 1.54 dependency.
It should be very easy to workaround the missing function I will put up a patch soon which will make it compile with >= 1.52.

**Comment by undingen** [comment]
If you have time you could try https://github.com/Percona-Lab/query-playback/pull/28 it should fix the errors you posted but I did not test it with a older boost version so there are maybe more problems.
I will take a look tomorrow.

**Comment by vadimtk** [comment]
after https://github.com/Percona-Lab/query-playback/pull/28

I am getting:

In file included from /opt/vadim/query/query-playback/percona_playback/query_log/query_log.h:27:0,
                 from /opt/vadim/query/query-playback/percona_playback/query_log/query_log.cc:27:
/usr/include/boost/utility/string_ref.hpp: In instantiation of â€˜boost::basic_string_ref<charT, traits>::size_type boost::basic_string_ref<charT, traits>::find(boost::basic_string_ref<charT, traits>) const [with charT = char; traits = std::char_traits<char>; boost::basic_string_ref<charT, traits>::size_type = long unsigned int]â€™:
/opt/vadim/query/query-playback/percona_playback/query_log/query_log.h:63:56:   required from here
/usr/include/boost/utility/string_ref.hpp:175:25: error: invalid conversion from â€˜long unsigned intâ€™ to â€˜boost::basic_string_ref<char, std::char_traits<char> >::const_iterator {aka const char*}â€™ [-fpermissive]
             return iter = this->cend () ? npos : std::distance ( this->cbegin (), iter );
                         ^
/usr/include/boost/utility/string_ref.hpp:175:88: error: invalid conversion from â€˜boost::basic_string_ref<char, std::char_traits<char> >::const_iterator {aka const char*}â€™ to â€˜boost::basic_string_ref<char, std::char_traits<char> >::size_type {aka long unsigned int}â€™ [-fpermissive]
             return iter = this->cend () ? npos : std::distance ( this->cbegin (), iter );
                                                                                        ^
make[2]: *** [percona_playback/query_log/CMakeFiles/query_log.dir/query_log.cc.o] Error 1
make[1]: *** [percona_playback/query_log/CMakeFiles/query_log.dir/all] Error 2

**Comment by undingen** [comment]
:-(
what distribution and version of gcc are you using? so that I can reproduce it tomorrow.

**Comment by vadimtk** [comment]
CentOS Linux release 7.3.1611 (Core)
gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)

**Comment by undingen** [comment]
I could reproduce it today.
It's a bug in boost 1.53 they do an assignment instead of a comparison. https://svn.boost.org/trac/boost/ticket/8067
I never run into this problem because I was using 1.54.

I will workaround it later today.
